name: "deploy"

on:
    push:
        branches: ["main"]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: 'Print'
              run: echo "bruh"
    test:
        runs-on: ubuntu-latest
        needs: deploy
        steps:
            - name: 'Print'
              run: echo "bruh 2"
