name: "deploy"

on:
    push:
        branches: ["main"]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: 'Print'
              run: a
            - name: Send Slack notification on failure
              if: failure()
              run: echo "fialed"
