name: "deploy"

on:
    push:
        branches: ["main"]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: '0'
              run: ls
            - name: '1'
              run: a
            - name: '2'
              run: echo "no"
            - name: Send Slack notification on failure
              if: failure()
              run: echo "fialed"
